LibraryLoader error
OSError                                   Traceback (most recent call
last)
<ipython-input-1-108c09baf5db> in <module>()
----> 1 import wrap_disembl.py

/Users/annettebradbury/disembl/disembl/wrap_disembl.py in <module>()
     14 # find and load the disembl.so executeable file
     15
---> 16 cfile = c.cdll.LibraryLoader('libdisembl.so')
     17 cfile.argstype = ['c_char_p', 'array_1d_float',
'array_1d_float',
     18                 'array_1d_float']

/Users/annettebradbury/anaconda/lib/python3.5/ctypes/__init__.py in
__getattr__(self, name)
    415         if name[0] == '_':
    416             raise AttributeError(name)
--> 417         dll = self._dlltype(name)
    418         setattr(self, name, dll)
    419         return dll

/Users/annettebradbury/anaconda/lib/python3.5/ctypes/__init__.py in
__init__(self, name, mode, handle, use_errno, use_last_error)
    345
    346         if handle is None:
--> 347             self._handle = _dlopen(self._name, mode)
    348         else:
    349             self._handle = handle

OSError: dlopen(LibraryLoader, 6): image not found